development:
  adapter: postgresql
  database: freefood_dev
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: freefood_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: freefood_prod
  host: localhost
  pool: 5
  timeout: 5000
